name: Build and Push to GHCR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      CONTAINER_NAME: 'nettools'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and tag image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/${{ env.CONTAINER_NAME }}:latest .

    - name: Push image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/${{ env.CONTAINER_NAME }}:latest
