name: Build and Push to GHCR

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 4 * * 1'  # minute hour day-of-month month day-of-week (1 = Monday)
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      CONTAINER_NAME: 'nettools'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Required for Docker Buildx
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    # Recommended for building multi-arch images
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push multi-arch image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ env.CONTAINER_NAME }}:latest
