name: Build and Push to Docker Hub

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 4 * * 1'  # minute hour day-of-month month day-of-week (1 = Monday)
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      CONTAINER_NAME: 'nettools'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Required for Docker Buildx
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Recommended for building multi-arch images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # NOTE: We use Docker Hub rather than GitHub's container registry because the docker/build-push-action action
      #   apparently produces container images that GitHub's container registry doesn't fully support (it will result
      #   in an unknown/unknown architecture). The only workaround is to disable provenance (see
      #   https://github.com/docker/build-push-action/issues/820#issuecomment-1482113833) but provenance improves
      #   the "trustworthiness" of the image. So, I'd rather leave it on.
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push multi-arch image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          # NOTE: We only use "latest" as tag as users will always want to use the latest (and thus only) image.
          #   There should be no point in using an older image. Also, this way we don't need to cleanup old images.
          tags:  ${{ vars.DOCKERHUB_USERNAME }}/${{ env.CONTAINER_NAME }}:latest
